### ISSUE TITLE
Error upon trying to import binfbx model

### ISSUE THREAD

**Issue by hax4dazy** [Kwizatz/control-modding#1]
I'm getting an error upon trying to import a binfbx model. 

This is the error: 
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_binfbx\importer.py", line 444, in execute
    for j in range(SemanticCount[INDEX]):
KeyError: 5`

The model I'm trying to import is located in `ep101-000-generic.bin` and is this model `drawers\metal_drawers_cabin_straight_high_var_c.binfbx`

**Comment by Kwizatz** [comment]
Thanks for the report, I'll try to reproduce and get back to you.

**Comment by Kwizatz** [comment]
Please try the new version, thanks!
